---
name: "Terminate LambdaLabs Instance"
description: "Terminates a Lambda Labs cloud instance using environment settings."
inputs:
  instance_id:
    description: "The ID of the instance to terminate"
    required: true
  lambda_token:
    description: "The LambdaLabs API token"
    required: true
  wait_for_termination:
    description: "Whether to wait for the instance to terminate"
    required: false
    default: "false"
  termination_timeout:
    description: "The timeout in seconds to wait for the instance to terminate"
    required: false
    default: "600"
runs:
  using: "composite"
  steps:
    - name: Copy requirements
      run: cp ${{ github.action_path }}/requirements.txt .tmp-ifera-lambdalabs-launch-instance-action-requirements.txt
      shell: bash

    - name: Set up Python
      id: setup-python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        cache: "pip"
        cache-dependency-path: .tmp-ifera-lambdalabs-launch-instance-action-requirements.txt

    - name: Install dependencies
      run: pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash

    - name: Terminate Instance
      id: terminate-instance
      run: python ${{ github.action_path }}/terminate_instance.py
      shell: bash
      env:
        INSTANCE_ID: ${{ inputs.instance_id }}
        LAMBDA_TOKEN: ${{ inputs.lambda_token }}
        WAIT_FOR_TERMINATION: ${{ inputs.wait_for_termination }}
        TERMINATION_TIMEOUT: ${{ inputs.termination_timeout }}

    - name: Clean up
      run: rm -f .tmp-ifera-lambdalabs-launch-instance-action-requirements.txt
      shell: bash
